name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.12
  - altair
  - ipykernel
  - jupyterlab
  - line_profiler
  - matplotlib
  - notebook
  - numpy=1.26.4
  - openpyxl
  - pandas=1.5.3
  - pip
  - pydantic
  - pytest
  - ruff
  - scipy
  - seaborn
  - vegafusion>=1.5.0
  - vegafusion-python-embed>=1.5.0
  - vl-convert-python

